### ISSUE TITLE
Add utility function for generating `inlineKeyboard`

### ISSUE THREAD

**Issue by orimiles5** [NivEz/telenode#6]
Hello there!

Firstly, I would like to thank you for creating and sharing your library. 

I wanted to share a suggestion with you regarding the creation of 
inline keyboards. While the current implementation works, I feel that it could benefit from a more concise approach.

Specifically, I think it would be helpful if the library included a utility function to create keyboards in a more consistent way. This would not only make it easier for users to create and customize their own keyboards, but also improve the overall usability of the library.

Here is an example of usage:
```js
const inlineKeyboard = createInlineKeyboard([['Start', 'start'], ['Say hello', 'hello'], ['Exit', 'exit']]);
```

I'm open to suggestions and would be happy to collaborate with you to improve the library in any way that I can. 

Thank you for taking the time to consider my suggestion.

Let me know your thoughts. I’d be happy to submit a PR.

**Comment by NivEz** [comment]
Hey!
Thank you for the willing to help and improve the library. It is verry appreciated. 

About your suggestion.
This utility function is actually a good idea, but it arises few questions:
* What about passing other options other than `callback_data`? (in your example you are using the `callback_data` as the seoncd item in the inner arrays). Personally I have never used other options in `InlineKeyboardButton` and I don't know how commonly they are used but acording to the docs https://core.telegram.org/bots/api#inlinekeyboardbutton there are few other options.
* Another problem is how would you structure the layout of the buttons? You can just use arrays and nested arrays for the structure but it is kinda similar to the original payload.

We can work on a clean solution together as I have few ideas for this.
Also in the bottom of the README (in the TODO list) I have a bunch of cool ideas to implement so I would be happy to collab.

Thanks again :)

**Comment by NivEz** [comment]
Hey!
Thank you for the willing to help and improve the library. It is verry appreciated.

About your suggestion.
This utility function is actually a good idea, but it arises few questions:

* What about passing other options other than `callback_data`? (in your example you are using the `callback_data` as the seoncd item in the inner arrays). Personally I have never used other options in `InlineKeyboardButton` and I don't know how commonly they are used but acording to the docs https://core.telegram.org/bots/api#inlinekeyboardbutton there are few other options.
* Another problem is how would you structure the layout of the buttons? You can just use arrays and nested arrays for the structure but it is kinda similar to the original payload.

We can work on a clean solution together as I have few ideas for this.
Also in the bottom of the README (in the TODO list) I have a bunch of cool ideas to implement so I would be happy to collab.

Thanks again :)

**Comment by orimiles5** [comment]
Thanks for your suggestions! 
I appreciate your enthusiasm to collaborate. 
I’ll consider your questions and come up with a solution that will work well for the library. 
I'lI get back to you soon with my thoughts on this as well as any ideas I have for the TODO list. 
Thank you!
